import uuid

from api import app

from fastapi.testclient import TestClient

from interview_agent.prompts import START_INTERVIEW, WAIT_FOR_USER_INTERRUPT_MESSAGE

client = TestClient(app)

valid_jd = """Full job description
SciTec has been awarded multiple government contracts and is growing our creative Team! SciTec, Inc. is a dynamic small business with the mission to deliver advanced sensor data processing technologies and scientific instrumentation capabilities in support of National Security and Defense. We support customers throughout the Department of Defense and U.S. Government in building innovative new tools to deliver unique world-class data exploitation capabilities.

Important Notice: SciTec exclusively works on U.S. government contracts that require U.S. citizenship for all employees. SciTec cannot sponsor or assume sponsorship of employee work visas of any type. Further, U.S. citizenship is a requirement to obtain and keep a security clearance. Applicants that do not meet these requirements will not be considered.

SciTec has an immediate opportunity for a talented RedHat Openshift Engineer to join our team in Boulder, CO. Successful applicants will bring deep experience with designing, deploying, and managing RedHat Openshift deployments in on-prem, hybrid, and cloud environments, a strong collaborative spirit, experience successfully mentoring junior team members, superior problem solving skills, and a clear focus on supporting customer needs.

Responsibilities

Design and implement RedHat Openshift deployments to meet customer requirements
Automate deployments form the infrastructure level to the platform level
Configure and install software, servers, routers and other network devices
Resolve issues tiers of support have escalated by troubleshooting deployed, cloud, and local deployments
Mentor team members on technical issues
Communicate with users to design and field optimal solutions
Maintain complete technical documentation
Other duties as assigned
Requirements

At least two years of professional experience building and maintaining Kubernetes environments with Redhat Openshift Container Platform version 4+
At least three years of professional experience using Linux operating systems
Strong understanding of Ansible playbooks
Strong understanding of Infrastructure as Code (IaC) solutions
The ability to obtain and maintain a DoD security clearance
Ability to obtain and maintain a DoD security clearance
Detail oriented
Good verbal and written communication skills
Candidates meeting the following criteria will be preferred:

Strong development experience using Docker, docker-compose, and/or Kubernetes
Experience deploying and maintaining CI/CD solutions for DevSecOps such as gitlab-ci and Jenkins
Experience developing ansible playbooks for process automation
Experience hardening Redhat Enterprise Linux Systems using DISA SCAP and STIGViewer
A Bachelor's degree in computer science, engineering, information technology or related field or equivalent experience
Experience with VMWare compute, storage, and network configurations
Dell server, switch and SAN configuration and maintenance experience
Ability to script with bash, python, or perl
An active DoD security clearance
Resumes, Cover Letters, and Applications which are generated by AI will not be considered for employment."""


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def prep_happy_path():
    response = client.post(
        "/prep",
        json={"job_description": valid_jd},
    )
    assert response.status_code == 200
    response_content = response.content
    assert response_content is not None
    assert len(response_content) > 1000


def prep_invalid_job_description():
    response = client.post(
        "/prep",
        json={"job_description": "This is a test job description" * 10},
    )
    assert response.status_code == 200
    response_content = response.content
    assert response_content is not None
    decoded_content = response_content.decode("utf-8")
    assert (
        "Invalid job description. Please provide a valid job description."
        in decoded_content
    )


def test_prep_empty_job_description():
    response = client.post(
        "/prep",
        json={"job_description": ""},
    )
    assert response.status_code == 422


def interview_happy_path():
    thread_id = str(uuid.uuid4())
    response = client.post(
        "/interview",
        json={"message": valid_jd, "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] == WAIT_FOR_USER_INTERRUPT_MESSAGE
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": START_INTERVIEW, "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] is not None  # Question 1
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": "Question 1 answer", "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] is not None  # question 2
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": "Question 2 answer", "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] is not None  # question 3
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": "Question 3 answer", "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] is not None  # question 4
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": "Question 4 answer", "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] is not None  # question 5
    assert decoded_content["feedback"] is None
    response = client.post(
        "/interview",
        json={"message": "Question 5 answer", "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] == "Interview complete"
    assert decoded_content["feedback"] is not None
    feedback = decoded_content["feedback"]
    assert feedback is not None
    assert len(feedback) == 5
    assert feedback[0]["similarity"] is not None
    assert feedback[0]["feedback"] is not None
    assert feedback[0]["qa"] is not None
    assert feedback[0]["qa"]["question"] is not None
    assert feedback[0]["qa"]["expected_answer"] is not None
    assert feedback[0]["qa"]["given_answer"] is not None
    """
    sample feedback for schema:
    [
        {
            "qa": {
                "question": "How can you serialize and deserialize a binary tree?",
                "expected_answer": "To serialize a binary tree, you can perform a pre-order traversal and store the values in a string. To deserialize, you can split the string and reconstruct the tree using the pre-order values.",
                "given_answer": "i dont know"
            },
            "similarity": 0,
            "feedback": "Your answer does not provide any relevant information regarding the serialization and deserialization of a binary tree, which significantly differs from the expected answer. A similarity score of 0.0 indicates no overlap between your response and the expected content."
        }
    ]
    """


def interview_invalid_job_description():
    thread_id = str(uuid.uuid4())
    response = client.post(
        "/interview",
        json={"message": "This is a test job description" * 10, "thread_id": thread_id},
    )
    assert response.status_code == 418
    response_json = response.json()
    print("response_json", response_json)
    assert response_json is not None
    assert response_json["message"] == "Please provide a valid job description"
    assert response_json["feedback"] is None
    # retry with valid job description
    response = client.post(
        "/interview",
        json={"message": valid_jd, "thread_id": thread_id},
    )
    assert response.status_code == 200
    decoded_content = response.json()
    assert decoded_content is not None
    assert decoded_content["message"] == WAIT_FOR_USER_INTERRUPT_MESSAGE
    assert decoded_content["feedback"] is None
