"""Define the state structures for the agent."""

from __future__ import annotations

import operator
from typing import Annotated, List, TypedDict

from pydantic import BaseModel, Field


class InputState(BaseModel):
    topic: str = Field(description="Topic of the interview")


class QA(BaseModel):
    question: str = Field(description="Question to be answered")
    expected_answer: str = Field(description="Expected answer to the question")
    given_answer: str = Field(description="Answer provided by the user")


class QAList(BaseModel):
    qa_list: List[QA] = Field(description="List of question and answers")


class Feedback(BaseModel):
    qa: QA = Field(description="Question and answer pair")
    similarity: float = Field(
        description="Similarity score between the expected answer and the given answer"
    )
    feedback: str = Field(description="Feedback to be generated by model")


class State(TypedDict):
    topic: str
    qa_list: List[QA]
    completed_qa: Annotated[list[QA], operator.add]
    feedback: List[Feedback]
