name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # skip CI if commit msg has [skip ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false
          BUILD_ENV: |
            ENV1=value
            ENVIORNEMENT2=${{ secrets.ENVIORNEMENT2 }}
